# Default development deployment
version: "3.9"

volumes:
  repository-service-tuf-storage:
  repository-service-tuf-api-data:
  repository-service-tuf-mq-data:
  repository-service-tuf-settings:
  repository-service-tuf-redis-data:
  repository-service-tuf-pgsql-data:

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    volumes:
     - "repository-service-tuf-mq-data:/var/lib/rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: "exit 0"
    restart: always

  postgres:
    image: postgres:15.1
    ports:
      # 5432 may already in use by another PostgreSQL on host
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - "repository-service-tuf-pgsql-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s

  repository-service-tuf-api:
    image: ghcr.io/repository-service-tuf/repository-service-tuf-api:${API_VERSION}
    volumes:
      - repository-service-tuf-api-data:/data
    ports:
      - 80:80
    environment:
      ##############################
      ### INFRASTRUCURE SERVICES ###
      ##############################
      - RSTUF_BROKER_SERVER="amqp://guest:guest@rabbitmq:5672"
      - RSTUF_REDIS_SERVER="redis://redis"
    depends_on:
      rabbitmq:
        condition: service_healthy

  localstack:
    image: localstack/localstack:2.2
    environment:
      HOSTNAME: "localstack"
      LOCALSTACK_HOST: "localstack"
      LS_LOG: "error"
    ports:
      - "4566:4566"

  web:
    image: python:3.10-slim-buster
    command: python -m http.server -d /var/opt/repository-service-tuf/storage 8080
    volumes:
      - repository-service-tuf-storage:/var/opt/repository-service-tuf/storage
    ports:
      - "8080:8080"

  redis:
    image: redis:4.0
    volumes:
      - repository-service-tuf-redis-data:/data
    ports:
      - "6379:6379"

  repository-service-tuf-worker:
    build:
      context: .
    entrypoint: "bash entrypoint-dev.sh"
    environment:
      - DATA_DIR=./data
      ###############################
      ### STORAGE BACKEND SERVICE ###
      ###############################
      - RSTUF_STORAGE_BACKEND=LocalStorage
      # LOCAL STORAGE
      # =============
      - RSTUF_LOCAL_STORAGE_BACKEND_PATH=/var/opt/repository-service-tuf/storage
      # AWS S3 STORAGE
      # ==============
      # - RSTUF_AWSS3_STORAGE_BUCKET=tuf-metadata
      # - RSTUF_AWSS3_STORAGE_ACCESS_KEY=access_key
      # - RSTUF_AWSS3_STORAGE_SECRET_KEY=secret_key
      # - RSTUF_AWSS3_STORAGE_REGION=us-east-1
      # - RSTUF_AWSS3_STORAGE_ENDPOINT_URL=http://localstack:4566
      ################################
      ### KEYVAULT BACKEND SERVICE ###
      ################################
      - RSTUF_KEYVAULT_BACKEND=LocalKeyVault
      # LOCAL KEYVAULT
      # ==============
      - RSTUF_LOCAL_KEYVAULT_PATH=/opt/repository-service-tuf-worker/tests/files/key_storage
      - RSTUF_LOCAL_KEYVAULT_KEYS=online.key,strongPass:online-rsa.key,strongPass,rsa
      ##############################
      ### INFRASTRUCURE SERVICES ###
      ##############################
      - RSTUF_BROKER_SERVER=amqp://guest:guest@rabbitmq:5672
      - RSTUF_SQL_SERVER=postgres:5432
      - RSTUF_SQL_USER=postgres
      - RSTUF_SQL_PASSWORD=secret
      - RSTUF_REDIS_SERVER=redis://redis
    volumes:
      - ./:/opt/repository-service-tuf-worker:z
      - repository-service-tuf-storage:/var/opt/repository-service-tuf/storage
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    tty: true
    stdin_open: true
