name: Tests and Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [ "3.9", "3.10", ]

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-versions }}

    - name: Install tox and coverage
      run: pip install tox tox-gh-actions

    - name: Run Python tests
      run: tox

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        fail_ci_if_error: false
        verbose: true

