name: Functional Tests

on:
  workflow_dispatch:
    inputs:
      docker_compose:
        description: "Docker Compose File"
        default: "docker-compose.yml"
        type: string
        required: False
      umbrella_branch:
        description: "Umbrella Branch (Functional Tests)"
        default: "main"
        type: string
        required: False
      api_version:
        description: "API Version"
        default: "latest"
        type: string
        required: False
      cli_version:
        description: "CLI Version"
        default: "latest"
        type: string
        required: False

  workflow_call:
    inputs:
      docker_compose:
        description: "Docker Compose File"
        default: "docker-compose.yml"
        type: string
        required: False
      umbrella_branch:
        description: "Umbrella Branch (Functional Tests)"
        default: "main"
        type: string
        required: False
      api_version:
        description: "API Version"
        default: "latest"
        type: string
        required: False
      cli_version:
        description: "CLI Version"
        default: "latest"
        type: string
        required: False

jobs:
  functional-das:
    name: "FT DAS"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RSTUF Worker Source Code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Checkout RSTUF Umbrella (FT)
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
            repository: repository-service-tuf/repository-service-tuf
            path: rstuf-umbrella
            ref: ${{ inputs.umbrella_branch }}

      - name: Run RSTUF Worker from source code
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: ${{ inputs.docker_compose }}
        env:
          API_VERSION: ${{ inputs.api_version }}

      - name: Run Functional Tests with Distributed Async Signing
        run: |
          make ft-das CLI_VERSION=${{ inputs.cli_version }}

  functional-signed:
    name: "FT Signed"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RSTUF Worker Source Code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Checkout RSTUF Umbrella (FT)
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          repository: repository-service-tuf/repository-service-tuf
          path: rstuf-umbrella
          ref: ${{ inputs.umbrella_branch }}

      - name: Run RSTUF Worker from source code
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: ${{ inputs.docker_compose }}
        env:
          API_VERSION: ${{ inputs.api_version }}

      - name: Run Functional Tests with Distributed Async Signing
        run: |
          make ft-signed CLI_VERSION=${{ inputs.cli_version }}